CREATE TABLE CATEGORY
(
    ID INT(11) AUTO_INCREMENT PRIMARY KEY,
    META_KEY VARCHAR(255),
    META_NAME VARCHAR(225),
    ID_PARENT INT(11),

    CONSTRAINT FOREIGN KEY (ID_PARENT) REFERENCES CATEGORY(ID)
);

CREATE TABLE MEMBER 
(
    ID INT(11) AUTO_INCREMENT PRIMARY KEY,
    NICKNAME VARCHAR(100),
    USERNAME VARCHAR(100),
    PASSWORD VARCHAR(100),
    EMAIL VARCHAR(100),
    THUMBNAIL VARCHAR(255)
);

CREATE TABLE PRODUCT
(
    ID VARCHAR(100) PRIMARY KEY,
    NAME VARCHAR(255),
    PRICE FLOAT ,
    DISCOUNT FLOAT,
    QUANTUM INT DEFAULT 0,
    STATUS BIT,
    DESCRIPTION VARCHAR(500),
    CONTENT TEXT,
    IMAGE VARCHAR(255),
    CREATE_AT DATETIME DEFAULT CURRENT_TIMESTAMP ,
    UPDATE_AT DATETIME DEFAULT CURRENT_TIMESTAMP ,
    ID_CATEGORY INT(11),
    ID_MEMBER INT(11),

    CONSTRAINT FOREIGN KEY(ID_MEMBER) REFERENCES  MEMBER(ID),
    CONSTRAINT FOREIGN KEY(ID_CATEGORY) REFERENCES CATEGORY(ID)
);

CREATE TABLE IMAGE
(
    ID INT(11) AUTO_INCREMENT  PRIMARY KEY,
    PATH_IMAGE VARCHAR(255),
    ID_PRODUCT VARCHAR(100),

    CONSTRAINT FOREIGN KEY(ID_PRODUCT) REFERENCES PRODUCT(ID)
);

CREATE TABLE CART
(
    ID INT(11) AUTO_INCREMENT PRIMARY KEY,
    CUSTOMER VARCHAR(255),
    EMAIL VARCHAR(255),
    PHONE VARCHAR(11),
    ADDRESS TEXT,
    STATUS INT,
    NOTE TEXT,
    CREATE_AT DATETIME  DEFAULT CURRENT_TIMESTAMP,
    SUCCESS_AT DATETIME,
    ID_MEMBER INT(11), 
    CONSTRAINT FOREIGN KEY(ID_MEMBER) REFERENCES MEMBER(ID) 
);

CREATE TABLE CART_DETAIL
(
    ID_CART INT(11),
    ID_PRODUCT VARCHAR(100),
    QUANTUM INT,
    PRIMARY KEY(ID_CART, ID_PRODUCT),
    CONSTRAINT FOREIGN KEY(ID_CART) REFERENCES CART(ID),
    CONSTRAINT FOREIGN KEY(ID_PRODUCT) REFERENCES PRODUCT(ID)
);